name: 'CTF Time'
on: 
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * 5"

jobs:
    ctf-time-to-discord:
        runs-on: ubuntu-latest
        steps:
            - name: install jq
              run: sudo apt update && sudo apt install jq -y;

            - name: get info via ctftime api
              run: |
               START=$(date -u +%s);
               END=$(date -u +%s -d "+7 days");
               curl -s "https://ctftime.org/api/v1/events/?limit=10&start=$START&end=$END" |jq > out.txt;
              shell: bash

            - name: send message via discord webhook
              shell: bash
              run: |
               echo "VARS: ${{ secrets.DISCORD_WEBHOOK_URL }}" "ENV: ${{ env.DISCORD_WEBHOOK_URL }}"
               LENGTH=$(cat out.txt|jq length);
               LENGTH=$(expr $LENGTH - 1);
               for i in $(seq 0 $LENGTH);
               do
                TITLE=$(cat out.txt|jq -r ".[$i].title"|xxd -c 1 -p |sed 's/^/\\u00/g'|tr --delete '\n');
                DESCRIPTION=$(cat out.txt|jq -r ".[$i].description"|xxd -c 1 -p |sed 's/^/\\u00/g'|tr --delete '\n');
                URL=$(cat out.txt|jq -r ".[$i].ctftime_url");
                IMG_URL=$(cat out.txt|jq -r ".[$i].logo");
                START_TIME=$(cat out.txt|jq -r ".[$i].start");
                curl "${{ vars.DISCORD_WEBHOOK_URL }}" -H 'Content-Type: application/json' -d "{\"embeds\": [{\"title\": \"$TITLE\",\"description\": \"$DESCRIPTION\",\"url\": \"$URL\",\"color\": 7419530,\"image\":{\"url\": \"$IMG_URL\"},\"timestamp\": \"$START_TIME\"}]}";
               done;