name: 'CTF Time'
on: 
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * 5"

jobs:
    ctf-time-to-discord:
        runs-on: ubuntu-latest
        steps:
            - name: install dependencies
              run: |
                sudo apt update && sudo apt install jq nodejs npm -y;
                sudo npm install -g prettier;

            - name: get info via ctftime api
              run: |
               START=$(date -u +%s);
               END=$(date -u +%s -d "+7 days");
               curl -s "https://ctftime.org/api/v1/events/?limit=100&start=$START&end=$END" |jq > out.txt;
              shell: bash

            - name: send message via discord webhook
              shell: bash
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: |
                LENGTH=$(jq length out.txt);
                LENGTH=$((LENGTH - 1));

                TABLE="| Title | Weight | Start Time | URL | Format |\n|---|---|---|---|---|";

                for i in $(seq 0 $LENGTH); do
                    TITLE=$(cat out.txt|jq -r ".[$i].title");
                    START_TIME_RAW=$(cat out.txt|jq -r ".[$i].start")
                    START_TIME=$(TZ=Asia/Kolkata date -d $START_TIME_RAW +"%d-%m-%Y %H:%M");
                    URL=$(cat out.txt|jq -r ".[$i].ctftime_url");
                    WEIGHT=$(cat out.txt|jq -r ".[$i].weight");
                    FORMAT=$(cat out.txt|jq -r ".[$i].format");

                    if [[ $(echo "$WEIGHT > 0" |bc -l) ]]; then
                      TABLE="$TABLE\n| $TITLE | $WEIGHT | $START_TIME | $URL | $FORMAT |";
                    fi
                done

                # Send as one message with Markdown table
                echo $TABLE > table.md;
                npx prettier table.md > formatted.md;

                cat formatted.md;

                curl -X POST "$DISCORD_WEBHOOK_URL" \
                  -F "payload_json={\"content\": \"Upccoming CTF's this week:\"}" \
                  -F "file[0]=@formatted.md"