name: 'CTF Time'
on: 
  workflow_dispatch:
  schedule:
    - cron: "30 17 * * 5"

jobs:
    ctf-time-to-discord:
        runs-on: ubuntu-latest
        steps:
            - name: install jq
              run: sudo apt update && sudo apt install jq -y;

            - name: get info via ctftime api
              run: |
               START=$(date -u +%s);
               END=$(date -u +%s -d "+7 days");
               curl -s "https://ctftime.org/api/v1/events/?limit=100&start=$START&end=$END" |jq > out.txt;
              shell: bash

            - name: send message via discord webhook
              shell: bash
              env:
                DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
              run: |
                LENGTH=$(jq length out.txt);
                LENGTH=$((LENGTH - 1));

                TABLE="| Title | Weight | Start Time | URL | Format |\n|---|---|---|---|---|";

                for i in $(seq 0 $LENGTH); do
                    TITLE=$(cat out.txt|jq -r ".[$i].title"|xxd -c 1 -p |sed 's/^/\\u00/g'|tr --delete '\n');
                    START_TIME=$(cat out.txt|jq -r ".[$i].start");
                    URL=$(cat out.txt|jq -r ".[$i].ctftime_url");
                    WEIGHT=$(cat out.txt|jq -r ".[$i].weight");
                    FORMAT=$(cat out.txt|jq -r ".[$i].format");

                    if [[ $(echo "$WEIGHT" > 0|bc -l) ]]; then
                      TABLE="$TABLE\n| $TITLE | $WEIGHT | $START_TIME | $URL | $FORMAT";
                    fi
                done

                # Send as one message with Markdown table
                TABLE=$(echo $TABLE)
                PAYLOAD=$(jq -n --arg content "Here are upcoming CTFs:\n\`\`\`md\n$TABLE\n\`\`\`" '{content: $content}');

                curl "$DISCORD_WEBHOOK_URL" \
                  -H "Content-Type: application/json" \
                  -d "$PAYLOAD"